const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.ScriptsInEvents.FolhaDeEventosFase1_Event2_Act3,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.ScriptsInEvents.FolhaDeEventosFaseFinal_Event3_Act3,
		C3.ScriptsInEvents.FolhaDeEventosFase2_Event4_Act3
	];
};
self.C3_JsPropNameTable = [
	{fundofase1: 0},
	{Sólido: 0},
	{Chão: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Personagem: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Áudio: 0},
	{Fixar: 0},
	{Névoa: 0},
	{fundofim: 0},
	{vidas: 0},
	{txtgameover: 0},
	{muro: 0},
	{chão2: 0},
	{Coração: 0},
	{Texto: 0},
	{fundodesafio1: 0},
	{fundoinicio: 0},
	{btnJogar: 0},
	{fundoFase2: 0},
	{Chão3: 0},
	{pedra: 0},
	{PlanoDeFundoEmBlocos: 0},
	{historia: 0},
	{btnproximo: 0},
	{img: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{fundoFaseFinal: 0},
	{Personagem2: 0},
	{Personagem3: 0},
	{lamparina: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Texto2: 0},
	{muro2: 0},
	{btnjogarnovamente: 0},
	{btnproximo2: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{txtTelaInicial: 0},
	{FonteDeSprites: 0},
	{triangulo: 0},
	{Sprite: 0},
	{Texto3: 0},
	{txt10: 0},
	{txt9: 0},
	{txt12: 0},
	{txt11: 0},
	{Senóide: 0},
	{pedraflutuante: 0},
	{espinhos: 0},
	{lava: 0},
	{FonteDeSprites2: 0},
	{FonteDeSprites3: 0},
	{txt24: 0},
	{txt25: 0},
	{txt22: 0},
	{txt23: 0},
	{txt26: 0},
	{calendario: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{FonteDeSprites4: 0},
	{BTNJOGARNOVAMENTE2: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{btnjogarnovamente3: 0},
	{Sprite2: 0},
	{Botão: 0},
	{vidas2: 0}
];

self.InstanceType = {
	fundofase1: class extends self.ITiledBackgroundInstance {},
	Chão: class extends self.ISpriteInstance {},
	Personagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Névoa: class extends self.ISpriteInstance {},
	fundofim: class extends self.ITiledBackgroundInstance {},
	vidas: class extends self.ITextInstance {},
	txtgameover: class extends self.ISpriteFontInstance {},
	muro: class extends self.ISpriteInstance {},
	chão2: class extends self.ISpriteInstance {},
	Coração: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	fundodesafio1: class extends self.ITiledBackgroundInstance {},
	fundoinicio: class extends self.ITiledBackgroundInstance {},
	btnJogar: class extends self.ISpriteInstance {},
	fundoFase2: class extends self.ITiledBackgroundInstance {},
	Chão3: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	historia: class extends self.ITextInstance {},
	btnproximo: class extends self.ISpriteInstance {},
	img: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	fundoFaseFinal: class extends self.ITiledBackgroundInstance {},
	Personagem2: class extends self.ISpriteInstance {},
	Personagem3: class extends self.ISpriteInstance {},
	lamparina: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	muro2: class extends self.ISpriteInstance {},
	btnjogarnovamente: class extends self.ISpriteInstance {},
	btnproximo2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	txtTelaInicial: class extends self.ITextInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	triangulo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	txt10: class extends self.ITextInstance {},
	txt9: class extends self.ITextInstance {},
	txt12: class extends self.ITextInstance {},
	txt11: class extends self.ITextInstance {},
	pedraflutuante: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	txt24: class extends self.ITextInstance {},
	txt25: class extends self.ITextInstance {},
	txt22: class extends self.ITextInstance {},
	txt23: class extends self.ITextInstance {},
	txt26: class extends self.ITextInstance {},
	calendario: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites4: class extends self.ISpriteFontInstance {},
	BTNJOGARNOVAMENTE2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	btnjogarnovamente3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {}
}